# Use the latest version of Ubuntu as the base image
FROM ubuntu:latest

# Update APT package lists
RUN apt-get update

# Upgrade installed software
RUN apt-get upgrade -y

# Print "Hello, World!" to the terminal
CMD echo "Hello, World!"