version: '3.8'

services:
  proxy:
    image: nginx:latest
    container_name: task6-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - back-end

  front-end:
    image: nginx:latest
    container_name: task6-front-end
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"

  back-end:
    image: python:3.9-slim
    container_name: task6-back-end
    environment:
      - FLASK_APP=app.py
    volumes:
      - ./backend:/app
    command: sh -c "cd /app && flask run --host=0.0.0.0 --port=5252"
    ports:
      - "5252"
    deploy:
      replicas: 2
